### ISSUE TITLE
"sh: ./bin/patch-enzyme.sh not found" in build pipeline

### ISSUE THREAD

**Issue by franfactor** [KevinGrandon/enzyme-react-16-context-patch#1]
It worked great locally, but I had the following error in gitlab pipeline:

"sh: ./bin/patch-enzyme.sh not found"

I have it working with 

`sh bin/patch-enzyme.sh`

**Comment by KevinGrandon** [comment]
Strange, I think that should work, but not sure of the setup. I'll go ahead and update this package, thanks for the bug!

**Comment by KevinGrandon** [comment]
Fixed by https://github.com/KevinGrandon/enzyme-react-16-context-patch/commit/c98e1045e4c2a58163db67c50606e5887392cea6
