### ISSUE TITLE
Feature Request: Make it work cross platform

### ISSUE THREAD

**Issue by dreadwail** [KevinGrandon/enzyme-react-16-context-patch#5]
Currently the patching scripts rely on SH scripts which don't work if you're on Windows. It would be great if we could make the scripts work cross-platform.

**Comment by KevinGrandon** [comment]
Thanks. If you’re using yarn, the better fix would be to use this fork: https://github.com/KevinGrandon/enzyme/tree/master/packages/enzyme-adapter-react-16

(I don’t have a windows machine to easily test on, but would definitely accept a pr)

**Comment by dreadwail** [comment]
Ah yea, we're not using Yarn so that wouldn't work for us. I can cook a PR for your patch and see what you think about it

**Comment by dreadwail** [comment]
FYI I ended up just using [patch-package](https://www.npmjs.com/package/patch-package) instead, with the patch file from this repo.

**Comment by dreadwail** [comment]
I'll close this issue since it seems unlikely that this will be important once Enzyme cuts a release
